# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

if(CMAKE_VERSION VERSION_LESS 3.0.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.0.0 or greater.")
endif()

if(CMAKE_VERSION VERSION_LESS 3.0.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.0.0 or greater.")
endif()

if(CMAKE_VERSION VERSION_LESS 3.0.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.0.0 or greater.")
endif()

if(CMAKE_VERSION VERSION_LESS 3.0.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.0.0 or greater.")
endif()

if(CMAKE_VERSION VERSION_LESS 3.0.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.0.0 or greater.")
endif()

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget vtkm_vectorization_flags vtkm_compiler_flags vtkm_developer_flags vtkm_diy vtkm_taotuple vtkm_cont)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target vtkm_vectorization_flags
add_library(vtkm_vectorization_flags INTERFACE IMPORTED)

set_target_properties(vtkm_vectorization_flags PROPERTIES
  INTERFACE_COMPILE_OPTIONS "\$<\$<COMPILE_LANGUAGE:CXX>:>"
)

# Create imported target vtkm_compiler_flags
add_library(vtkm_compiler_flags INTERFACE IMPORTED)

set_target_properties(vtkm_compiler_flags PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_11"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/paraview-5.6"
  INTERFACE_LINK_LIBRARIES "vtkm_vectorization_flags"
)

# Create imported target vtkm_developer_flags
add_library(vtkm_developer_flags INTERFACE IMPORTED)

set_target_properties(vtkm_developer_flags PROPERTIES
  INTERFACE_COMPILE_OPTIONS "\$<\$<COMPILE_LANGUAGE:CXX>:-Wall;-Wno-long-long;-Wcast-align;-Wconversion;-Wchar-subscripts;-Wextra;-Wpointer-arith;-Wformat;-Wformat-security;-Wshadow;-Wunused-parameter;-fno-common>"
)

# Create imported target vtkm_diy
add_library(vtkm_diy INTERFACE IMPORTED)

set_target_properties(vtkm_diy PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_auto_type"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/paraview-5.6/vtkm/thirdparty/diy"
)

# Create imported target vtkm_taotuple
add_library(vtkm_taotuple INTERFACE IMPORTED)

set_target_properties(vtkm_taotuple PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_auto_type"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/paraview-5.6/vtkm/thirdparty/taotuple"
)

# Create imported target vtkm_cont
add_library(vtkm_cont SHARED IMPORTED)

set_target_properties(vtkm_cont PROPERTIES
  INTERFACE_LINK_LIBRARIES "vtkm_compiler_flags;vtkm_diy;vtkm_taotuple"
)

# Import target "vtkm_cont" for configuration "Debug"
set_property(TARGET vtkm_cont APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(vtkm_cont PROPERTIES
  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/lib/libvtkm_cont-pv5.6.so.1"
  IMPORTED_SONAME_DEBUG "libvtkm_cont-pv5.6.so.1"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
