name: headless_windows

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:

    - uses: actions/checkout@v4
      name: Checkout TTK-ParaView source code

    - uses: prefix-dev/setup-pixi@v0.9.6
      with:
        run-install: false

    - name: Create ParaView package
      run: |
        pixi build

    - name: Upload install executable
      uses: actions/upload-artifact@v7
      with:
        path: "*.conda"

  test:
    needs: build
    runs-on: windows-latest
    steps:

    - name: Download artifacts
      uses: actions/download-artifact@v8

    - uses: prefix-dev/setup-pixi@v0.9.6
      with:
        run-install: false

    - name: Install package
      shell: bash
      run: |
        pixi init
        pixi add $PWD/*.conda

    - name: Test Python imports
      shell: pixi run bash -e {0}
      run: |
        echo "\npython vtk"
        python -c "import vtk"
        echo "\npvpython vtk"
        pvpython -c "import vtk"
        echo "\npvpython paraview simple"
        pvpython -c "from paraview.simple import *"
        echo "\npython paraview simple"
        python -c "from paraview.simple import *"
