# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branch-ignore:
      - '*'
    tags:
      - 'v*'
      - 'dev*'
      - '*.*.*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Remove hosted Python
      run: |
        sudo rm -rf /usr/local/Frameworks/Python.framework

    - name: Install macOS dependencies
      run: |
        brew install --cask xquartz
        brew install wget libomp mesa glew boost qt@5 ninja python
        echo $(brew --prefix python)

    - name: Configure ParaView build
      run: |
        # switch to Xcode 11 since Xcode 12 breaks the ParaView build
        sudo xcode-select -s "/Applications/Xcode_11.7.app"
        mkdir build && cd build
        cmake \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INSTALL_PREFIX=/Applications \
          -DQt5_DIR=$(brew --prefix qt@5)/lib/cmake/Qt5 \
          -DPython3_ROOT_DIR=$(brew --prefix python) \
          -GNinja \
          $GITHUB_WORKSPACE
