# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install Ubuntu dependencies
      run: |
        sudo apt update
        # ParaView dependencies
        sudo apt install -y \
          qt5-default \
          qttools5-dev \
          qtxmlpatterns5-dev-tools \
          libqt5x11extras5-dev \
          libqt5svg5-dev \
          dpkg-dev

    - name: Cache ParaView .deb package
      id: cache-paraview
      uses: actions/cache@v2
      with:
        path: build/ttk-paraview.deb
        key: ${{ runner.os }}-pv-deb-v5.8.0

    - name: Build & install patched ParaView
      if: steps.cache-paraview.outputs.cache-hit != 'true'
      run: |
        mkdir build && cd build
        cmake \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INSTALL_PREFIX=/usr \
          -DVTK_ENABLE_OSPRAY=OFF \
          $GITHUB_WORKSPACE
        make -j$(nproc) package
        sudo dpkg -i ttk-paraview.deb
